### ISSUE TITLE
Data/ValueSetter.hpp: No such file or directory

### ISSUE THREAD

**Issue by ali32b** [bblanchon/ArduinoJson#685]
After updating to 5.13.1 I get this error:
\Documents\Arduino\libraries\ArduinoJson\src/ArduinoJson/JsonArray.hpp:10:32: fatal error: Data/ValueSetter.hpp: No such file or directory

 #include "Data/ValueSetter.hpp"

compilation terminated.

**Comment by bblanchon** [comment]
Hi @ali32b,

Sometimes, the Arduino LIbrary Manager doesn't upgrade the library correctly.
In this situation, you just need to uninstall and reinstall ArduinoJson.

Regards,
Benoit

**Comment by ali32b** [comment]
Thank you @bblanchon,I did and problem solved.
